name: Build Android APK for Play Store

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm ci
      
    - name: Build web assets
      run: node capacitor-build.js
      
    - name: Decode Keystore
      if: github.event_name != 'pull_request'
      run: |
        if [ "${{ secrets.KEYSTORE_BASE64 }}" != "" ]; then
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > android/app/release-key.keystore
        fi
        
    - name: Build Debug APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon
        
    - name: Build Release APK
      if: github.event_name != 'pull_request' && secrets.KEYSTORE_BASE64
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon
        
    - name: Build AAB for Play Store
      if: github.event_name != 'pull_request' && secrets.KEYSTORE_BASE64
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        cd android
        ./gradlew bundleRelease --no-daemon
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: firstmove-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Release APK
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: firstmove-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Upload AAB for Play Store
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: firstmove-release-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          android/app/build/outputs/apk/release/app-release.apk
          android/app/build/outputs/bundle/release/app-release.aab
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}